### ISSUE TITLE
Icon Request: Riot

### ISSUE THREAD

**Issue by KSXGitHub** [numixproject/numix-core#4243] opened 2018-02-28 16:44 UTC
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Riot | `riot` | `riot.desktop` | ![Riot](https://i.imgur.com/HnNA5Wd.png)| Numix-Circle |

**Description:** Riot is a Matrix.org client a.k.a. a chat/message app

**Website:** http://riot.im/

---

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by palob** [comment] 2018-02-28 18:20
duplicate of #3812 and#3981.

Looks like you're using an outdated version of our theme. How did you install?

**Closed as completed by palob** 2018-02-28 18:20 UTC
Labels: duplicate

**Comment by KSXGitHub** [comment] 2018-02-28 18:43
I use numix-icon-theme-git from Arch Linux AUR

**Comment by palob** [comment] 2018-02-28 19:22
Could you please notify the maintainer that the package is severely out of date?
https://aur.archlinux.org/packages/numix-circle-icon-theme-git/

**Comment by Foggalong** [comment] 2018-02-28 19:53
How has a -git package even managed to get that out of date!?

**Comment by KSXGitHub** [comment] 2018-02-28 20:12
@Foggalong I always upgrade everything using `yaourt -Su --aur`  hence I only get to upgrade numix when package author bumbs up the version. Of course I could simply reinstall that package but I didn't know that before

**Comment by palob** [comment] 2018-02-28 20:18
@Foggalong I suspect they never switched to the new package repo but rather still try to build from core which used to be the circle repo.

**Comment by Foggalong** [comment] 2018-02-28 20:38
Ahhh, that would explain it.
