### ISSUE TITLE
Icon for Vivaldi

### ISSUE THREAD

**Issue by cdysthe** [numixproject/numix-core#3531] opened 2016-12-23 00:30 UTC
Please add an icon for Vivaldi:

[Desktop Entry]
Version=1.0
Name=Vivaldi
GenericName=Web Browser
Exec=/usr/bin/vivaldi-stable %U
Terminal=false
Icon=vivaldi
Type=Application
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml_xml;image/webp;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;

**Comment by palob** [comment] 2016-12-23 00:37
[We've got a Cicle icon](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/vivaldi.svg) for quite a time, duplicate of #1510.

The Square icon is soon to be merged #3516.

**Closed as completed** 2016-12-23 00:37 UTC
Labels: duplicate
