### ISSUE TITLE
Icon Request : Mailspring

### ISSUE THREAD

**Issue by l3lackcurtains** [numixproject/numix-core#4203] opened 2018-02-12 11:59 UTC
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Mailspring | `mailspring` | `mailspring.desktop` | ![Mailspring](https://i.imgur.com/YruuLCX.png)| Numix-Circle |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by palob** [comment] 2018-02-12 19:25
Duplicate of #3946

**Closed as completed by palob** 2018-02-12 19:25 UTC
Labels: duplicate, linux
