### ISSUE TITLE
Icon Request: Fractal

### ISSUE THREAD

**Issue by KSXGitHub** [numixproject/numix-core#4244] opened 2018-02-28 16:47 UTC
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Fractal | `org.gnome.Fractal` | `org.gnome.Fractal.desktop` | ![Fractal](https://i.imgur.com/x5siqLi.png)| Numix-Circle |

**Description:** Fractal is a GTK+ client for Matrix.org — a messaging app

**Website:** https://github.com/danigm/fractal 

---

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by palob** [comment] 2018-02-28 18:19
duplicate of #4244

**Closed as completed by palob** 2018-02-28 18:19 UTC
Labels: duplicate
