### ISSUE TITLE
update icon Kdenlive

### ISSUE THREAD

**Issue by ramzydoni** [numixproject/numix-core#3805] opened 2017-06-29 11:39 UTC
hello i try install numix icon is very great icon and project
but the note is that some icon are still as old and unexplained as the " kdenlive"
i think need update 
new logo 
http://www.omgubuntu.co.uk/wp-content/uploads/2016/08/new-kdenlive-logo.png

**Comment by palob** [comment] 2017-06-29 11:43
duplicate of #3415.

**Closed as completed by palob** 2017-06-29 11:43 UTC
Labels: duplicate
