### ISSUE TITLE
Icon Request: GitKraken

### ISSUE THREAD

**Issue by AlexisSniffer** [numixproject/numix-core#3512] opened 2016-11-25 02:05 UTC
Icon Request: GitKraken

[Desktop Entry]
Name=GitKraken
Comment=Unleash your repo
GenericName=Demo Application
Exec=/usr/share/gitkraken/gitkraken %U
Icon=app
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Development;Documentation;
MimeType=text/plain;

![app](https://cloud.githubusercontent.com/assets/9704531/20612576/714458be-b289-11e6-831e-aad0df0d7b30.png)

**Comment by palob** [comment] 2016-11-25 07:51
Duplicate of #2880. We can't cover it due to the generic icon name ``app``. Please ask the devs/packagers to change it to something more specific.

**Closed as completed** 2016-11-25 11:03 UTC
Labels: duplicate
