### ISSUE TITLE
fcitx icons all lost in indicator tray

### ISSUE THREAD

**Issue by gehuangyi20** [numixproject/numix-core#3699] opened 2017-04-29 15:57 UTC
I am using numix-circle as my icon theme. The fcitx icon in the system menu tray all lost. They all becomes the default keyboard. If I am using numix as my icon theme, the icons are there.

Original issue: [https://github.com/numixproject/numix-icon-theme-circle/issues/50](url)

Screen shot for Numix-Circle
![1](https://cloud.githubusercontent.com/assets/3879058/25548847/8576ca2e-2c3c-11e7-98af-47cdd50218ea.png)

Screen shot for Numix
![2](https://cloud.githubusercontent.com/assets/3879058/25548927/ea8c7c1a-2c3c-11e7-873d-6a62ec511b23.png)

In the theme Numix-Circle it tries to using icon ![fcitx](https://cloud.githubusercontent.com/assets/3879058/25556642/fc081738-2ccd-11e7-87c1-fdb3cf216809.png) to replace icon ![fcitx](https://cloud.githubusercontent.com/assets/3879058/25556640/f56d2e2c-2ccd-11e7-89c3-5cce481208e8.png)

However, I found that all icons with prefix `"fcitx"` such as (fcitx-pinyin ![fcitx-sunpinyin](https://cloud.githubusercontent.com/assets/3879058/25556671/658d5f7e-2cce-11e7-9e3c-e70a74d0f2e3.png) , fcitx-anthy ![fcitx-anthy](https://cloud.githubusercontent.com/assets/3879058/25556687/be989d68-2cce-11e7-91b5-e19381904d28.png) ) are replaced by the icon `"fcitx"`![fcitx](https://cloud.githubusercontent.com/assets/3879058/25556642/fc081738-2ccd-11e7-87c1-fdb3cf216809.png) under folder `"/usr/share/icons/Numix-Circle/48/apps/fcitx.svg"` which is a symbolic link to `"/usr/share/icons/Numix-Circle/48/apps/fcitx.svg"` . I tried to renamed `fcitix.svg` to some other name like `fcitix.svg.bak` and rebuild the icon cache. In that case, icons with prefix `fcitx` are found.

I read the index.theme of Numix-CIrcle. It sets the icon with size 48 having context `Application` and type `Scaleable` from 8 to 512. Is this setting too aggresive which cause the issue?

**Comment by Foggalong** [comment] 2017-05-17 20:58
@gehuangyi20 The problem is we don't currently provide the icons in any other sizes, which we really should be doing. It's a hell of a lot of work to make that happen though: around 30,000+ icons to make :cry:

**Comment by gehuangyi20** [comment] 2017-05-17 21:52
@Foggalong Sorry for that. The icon is svg. I think there is no reason to remake it. The program can scale the icon. Is it possible to write a script to auto-generate the symbolic link? It may work.

**Comment by Foggalong** [comment] 2017-05-18 07:58
@gehuangyi20 In theory yeah because it's SVG you could just scale it with a script (the likes of which we already have) but if we did that then it'd make really blurry symbols because it'd be trying to fit the same amount of detail into ¼ of the space.

**Comment by Foggalong** [comment] 2017-12-24 16:05
I'm gonna wontfix this because at the moment it's just too big a project for us to properly take on.

**Closed as completed by Foggalong** 2017-12-24 16:05 UTC
Labels: bug, enhancement, wontfix
