### ISSUE TITLE
Postman

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#3886] opened 2017-08-13 19:45 UTC
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Postman`| `postman` | `postman.desktop` | ![postman](https://user-images.githubusercontent.com/7660997/29252914-a1d56c6a-8070-11e7-83b0-fb4ab5d377d7.png)|

Description: `Build, test, and document your APIs faster`

Website: `https://www.getpostman.com/`

**Comment by Foggalong** [comment] 2017-08-13 21:38
Duplicate of #2443, not sure why that one was ever closed

**Closed as completed by Foggalong** 2017-08-13 21:38 UTC
Labels: duplicate
