### ISSUE TITLE
Goland Icon

### ISSUE THREAD

**Issue by alrightjulian** [numixproject/numix-core#4969] opened 2019-08-21 22:07 UTC
| Application Name | Icon Name | Desktop File Name | Original icon |
| --- | :-- | :-- | :-- |
| `goland`| `goland` | `goland` | ![original](https://pbs.twimg.com/profile_images/809358866442055680/CZjD2GYK_400x400.jpg) |

Description: `Jetbrain IDE for golang, goland`

Website: `https://www.jetbrains.com/go/`

**Comment by palob** [comment] 2019-08-22 15:49
duplicate of #4198

**Closed as completed by palob** 2019-08-22 15:49 UTC
Labels: duplicate, linux
